#!/bin/bash

################################################################################
#
# diffsem
# =======
#
# This bash script compares the current state of files in a git repository
# with a specified commit. Unlike a `git diff`, however, the resulting 
# output is a set of files containing the full* source code of all modified
# files, where each new or modified line is prepended by a "+".
#
# Usage:
# diffsem <repo> <pattern> <commit>
#
# <repo> - the path to the git repository
# <pattern> - grep pattern matching the filenames/paths to be compared
# <commit> - the commit to compare with
#
# The generated text files are placed in ./diff (that is, a directory 'diff' 
# within the current working directory).
#
# Copyright (c) 2016 Jani Bonnevier
#
# Released under the terms of the MIT License, see the file "LICENSE".
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


if [ -z "$3" ]; then 
	echo Please provide three arguments:
	echo "diffsem <repo> <pattern> <commit>"
	exit 1
fi

repopath=${1%/}
codedir=$2
commit=$3

outfolder=$PWD/diff
postfix=_diffsem.txt

function gen_diff {
	local commit_l=$1
	local infile_l=$2
	local outfolder_l=$3
	local postfix_l=$4

	local outfile=$outfolder_l/$(basename $infile_l)$postfix_l

	git diff --unified=100000 $commit_l -- $infile_l > $outfile
	sed -i '/^-/d' $outfile
	sed -i '/^diff --git/d' $outfile
	sed -i '/^index /d' $outfile
	sed -i '/^+++ /d' $outfile
	sed -i '/^@@.*@@$/d' $outfile
	sed -i '/^new file /d' $outfile
	echo Created $outfile
}

echo Creating output folder...
mkdir -p $outfolder

cd $repopath

echo Finding changed files...
git diff $commit -- $repopath > $outfolder/ALL_CHANGES$postfix
git diff --name-only $commit -- $repopath | grep $codedir > \
$outfolder/CHANGED_SOURCES$postfix

echo Creating diffs...
while read file; do
	gen_diff $commit $repopath/$file $outfolder $postfix;
done < $outfolder/CHANGED_SOURCES$postfix

echo Done.
exit 0
